ROOTAPP/urls.py
from django.urls import path

from ROOTAPP.views import (ByNowView, CheckoutView, ProductActionsView,
                           add_email, del_user_phone,
                           get_and_check_registration_phone,
                           get_registration_name,
    # google_response,
                           logout_view,
                           regenerate_sms_token,
    # request_google_auth,
                           update_user_personal, update_user_phones,
                           verify_sms_token, get_settlement_info, ajax_updates_person_phones_info, ajax_phone_field,
                           ajax_person_field, ajax_change_phone_parameters)
from finance.views import MovementOfGoods

app_name = 'root_app'
urlpatterns = [
    path('product_actions/', ProductActionsView.as_view(), name='product_actions'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('by_now/', ByNowView.as_view(), name='by_now'),
    path('get_and_check_registration_phone/', get_and_check_registration_phone, name='get_and_check_registration_phone'),
    path('get_registration_name/', get_registration_name, name='get_registration_name'),
    path('regenerate_sms_token/', regenerate_sms_token, name='regenerate_sms_token'),
    path('verify_sms_token/', verify_sms_token, name='verify_sms_token'),
    path('logout/', logout_view, name='logout'),
    path('add_email/', add_email, name='add_email'),
    path('update_user_personal/', update_user_personal, name='update_user_personal'),
    path('update_user_phones/', update_user_phones, name='update_user_phones'),
    path('del_user_phone/', del_user_phone, name='del_user_phone'),
    path('get_settlement_info/', get_settlement_info, name='get_settlement_info'),
    path('ajax_updates_person_phones_info/<str:mode>', ajax_updates_person_phones_info, name='ajax_updates_person_phones_info'),
    path('ajax_phone_field/<str:mode>', ajax_phone_field, name='ajax_phone_field'),
    path('ajax_person_field/<str:mode>', ajax_person_field, name='ajax_person_field'),
    path('ajax_change_phone_parameters/', ajax_change_phone_parameters, name='ajax_change_phone_parameters'),
    # path('request_google_auth/', request_google_auth, name='request_google_auth'),
    # path('google_response/', google_response, name='google_response'),
]

Shop_DJ/urls.py
from baton.autodiscover import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import include, path

admin.site.site_header = 'Снип-Сноп'
admin.site.site_title = "Главная страница"
admin.site.index_title = 'Панель администрирования интернет-магазина "Снип-Сноп"'

urlpatterns = [

    path("select2/", include("django_select2.urls")),
    path('admin/', admin.site.urls),
    path("dynamic-admin-form/", include("dynamic_admin_forms.urls")),
    path('baton/', include('baton.urls')),
    path('accounts/', include('allauth.urls')),
    path('finance/', include('finance.urls')),
    path('nova_poshta', include('nova_poshta.urls')),
    path('root_app/', include('ROOTAPP.urls')),
    path('orders/', include('orders.urls')),
    path('', include('main_page.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_page/urls.py
from django.urls import path

from .views import (CabinetView, CompareView, FavoritesView, MainPageView,
                    dispatch_view)

urlpatterns = [

    path('', MainPageView.as_view(), name='home'),
    # path('<slug:slug>/', CatalogRoutingVew.as_view()),
    path('favorites/', FavoritesView.as_view(), name='favorites'),
    path('compare/', CompareView.as_view(), name='compare'),
    path('cabinet/', CabinetView.as_view(), name='cabinet'),
    path('<slug:slug>/', dispatch_view, name='category_and_product'),
    path('<slug:slug>/<str:str_url_data>/', dispatch_view, name='filteres_category'),
]
app_name = 'main_page'

orders/urls.py
from django.urls import path

from orders.views import (cancel_oneclick, create_one_click_order,
                          oneclick_add_comment, pre_create_order, get_person_info_ajax,
                          get_persons_and_contacts_by_phone_ajax, button_add_number_to_person_ajax)

urlpatterns = [
    path('by_one_click/', create_one_click_order, name='by_one_click'),
    path('oneclick_add_comment', oneclick_add_comment, name='oneclick_add_comment'),
    path('cancel_oneclick', cancel_oneclick, name='cancel_oneclick'),
    path('pre_create_order', pre_create_order, name='pre_create_order'),
    path('get_person_info_ajax', get_person_info_ajax, name='get_person_info_ajax'),
    path('get_persons_and_contacts_by_phone_ajax', get_persons_and_contacts_by_phone_ajax,
         name='get_persons_and_contacts_by_phone_ajax'),
    path('button_add_number_to_person_ajax', button_add_number_to_person_ajax, name='button_add_number_to_person_ajax'),
]
app_name = 'orders'

main_page/views.py
import django
from django.contrib.postgres.aggregates import ArrayAgg
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView, View

from catalog.models import Category, Product, ProductImage
from catalog.views import CategoryView, ProductView
from main_page.models import (Banner, Menu, NewProduct, PopularCategory,
                              PopularProduct, Schedule, SitePhone)
from ROOTAPP.forms import PersonalInfoForm
from ROOTAPP.models import Messenger, PersonPhone
from site_settings.models import (HeaderConfiguration, PhotoPlug,
                                  SliderConfiguration)


class MainPageView(TemplateView):
    template_name = 'main-page/index.html'

    def get_context_data(self, **kwargs):
        print('CSRF = ', django.middleware.csrf.get_token(self.request))
        context = super().get_context_data(**kwargs)
        context |= {
            'banners': Banner.objects.all(),
            'slider_config': SliderConfiguration.get_solo(),
            'popular_categories': PopularCategory.objects.all(),
            'popular_products': PopularProduct.with_price.all(),
            'new_products': NewProduct.with_price.all(),
        }
        return context


def group_products_by_categories(id_list):
    grouped_dict = dict()
    for product in Product.with_price.filter(id__in=id_list):
        product_main_category = Category.objects.filter(productplacement__product=product).order_by('level').first()
        if product_main_category.slug in grouped_dict.keys():
            grouped_dict[product_main_category.slug]['products'].append(product)
        else:
            grouped_dict[product_main_category.slug] = {
                'category': product_main_category,
                'products': [product]
            }
    return grouped_dict


class FavoritesView(TemplateView):
    template_name = 'main-page/favorites.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id_list = [int(product_id) for product_id in self.request.session.get('favorites', list())]
        context['grouped_dict'] = group_products_by_categories(id_list)
        return context


class CompareView(TemplateView):
    template_name = 'main-page/compare.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        id_list = [int(product_id) for product_id in self.request.session.get('compare', list())]
        categories_data = group_products_by_categories(id_list)
        for category_data in categories_data.items():
            category = category_data[1]['category']
            products = category_data[1]['products']
            second_categories = [sc for sc in Category.objects.filter(
                productplacement__product__in=products).exclude(id=category.id).distinct()]
            category_data[1]['second_categories'] = second_categories

        context['grouped_dict'] = categories_data
        return context


@csrf_exempt
def dispatch_view(request, slug, str_url_data=None):
    for model in (Category, Product):
        if model.objects.filter(slug=slug).exists():
            return {'product': ProductView, 'category': CategoryView}.get(
                model.__name__.lower()).as_view()(request, slug=slug, str_url_data=str_url_data)


class CabinetView(TemplateView):
    template_name = 'main-page/cabinet.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        person = self.request.user
        person_phones = PersonPhone.objects.filter(person=person).annotate(
            m_id_list=ArrayAgg('phone__messengers', ordering='phone__messengers'),
            # str_phone=models.Value(person, output_field=models.CharField())
        ).values(
            'id', 'phone__number', 'm_id_list', 'phone'
        )
        main_phone_id_query = PersonPhone.objects.filter(
                phone_id=self.request.user.main_phone, person=self.request.user
            )
        delivery_phone_id_query = PersonPhone.objects.filter(
                phone_id=self.request.user.delivery_phone, person=self.request.user
            )
        context |= {
            'personal_info_form': PersonalInfoForm(instance=person),
            'person_phones': person_phones,
            # 'person_phones': PersonPhone.objects.filter(person=person),
            'messengers': Messenger.objects.all(),
            'main_phone_id': main_phone_id_query.first().id if main_phone_id_query.exists() else None,
            'delivery_phone_id': delivery_phone_id_query.first().id if delivery_phone_id_query.exists() else None,
            'phones_one': len(person_phones) == 1
        }
        return context

templates/main-page/admin_schedule_include_top.html
<br>
<h5> <i>Если день недели выходной оставьте поля времени пустыми</i></h5>
<br>

templates/main-page/cabinet.html
{% extends 'template_with_header_footer.html' %}
{% load i18n %}
{% load socialaccount %}
{% load custom_tags %}

{% block title %}
    <title> Сніп-Сноп | Особистий кабінет</title>
{% endblock title %}

{% block content %}
    <div class="content-wrapper cabinet-detail">
        <h2>Мій особистий кабінет</h2>
        <div>
            <!-- Кнопки -->
            <ul class="cabinet-detail-tabs-nav">
                <li><a href="#tab-1">Персональні дані</a></li>
                <li><a href="#tab-2">Мої номери</a></li>
                <li><a href="#tab-3">Мої адреси</a></li>

            </ul>

            <!-- Контент -->
            <div class="cabinet-detail-tabs-items">
                <div class="cabinet-detail-tabs-item login" id="tab-1">
                    <div class="center_form_wrapper">
                        <form action="{% url 'root_app:update_user_personal' %}" id="personalInfoForm">
                            {{ personal_info_form.as_p }}
                            <button type="submit" style="display: none;">Збрегти зміни</button>
                        </form>
                    </div>

                </div>
                <div class="cabinet-detail-tabs-item login" id="tab-2">
                    <div class="center_form_wrapper cabinet-phones">
                        <form action="{% url 'root_app:update_user_phones' %}" id="updateUserPhones" data-delivery-id="{{ delivery_phone_id }}" data-main-id="{{ main_phone_id }}">
                            <div class="cabinet-phones-table">
                                <div class="cabinet-phones-header">
                                    Номер телефону
                                </div>
                                <div class="cabinet-phones-header">
                                    Месенжери
                                </div>
                                <div class="cabinet-phones-header">
                                    Номер вказується для доставки
                                </div>
                                <div class="cabinet-phones-header">
                                    Номер входу в особистий кабінет
                                </div>
                                <div></div>

                                {% for person_phone in person_phones %}
                                    {% if person_phone.phone__number %}

                                        <div class="cabinet-phones-column cabinet-phones-phone" data-id={{ person_phone.id }}>
                                            <span>+38 (0</span>
                                            <input class="phone-number-input {% val_if_eq person_phone.id main_phone_id 'disabled' %}" name="phone_{{ person_phone.id }}" type="text" autocomplete="off" value="{{ person_phone.phone__number | strip_phone }}" {% val_if_eq person_phone.id main_phone_id 'disabled' %} data-valid="true" data-wrong-values="">
                                        </div>
                                        <div class="cabinet-phones-column cabinet-phones-messangers" data-id={{ person_phone.id }}>
                                            {% for m in messengers %}
                                                <label>
                                                    {{ m }}
                                                    <input type="checkbox" name="messengers_{{ person_phone.id }}" value="{{ m.id }}" {% val_when_in m.id person_phone.m_id_list 'checked' %}>
                                                    <div class="checkbox--visible"></div>
                                                </label>
                                            {% endfor %}
                                        </div>
                                        <div class="cabinet-phones-column cabinet-phones-radios" data-id={{ person_phone.id }}>
                                            <label>
                                                <input type="radio" name="is_delivery_phone" value="{{ person_phone.id }}" {% val_if_eq person_phone.id delivery_phone_id 'checked' %}>
                                                <div class="checkbox--visible checkbox--visible-radio"></div>
                                            </label>
                                        </div>

                                        <div class="cabinet-phones-column cabinet-phones-radios" data-id={{ person_phone.id }}>
                                            <label>
                                                <input type="radio" name="is_main_phone" value="{{ person_phone.id }}" {% val_if_eq person_phone.id main_phone_id 'checked' %}>
                                                <div class="checkbox--visible checkbox--visible-radio"></div>
                                            </label>
                                        </div>
                                        <div class="cabinet-phones-column del-row" data-id='{{ person_phone.id }}' data-new='no' style="{% values_by_condition phones_one 'display: none;' %}">
                                            <div class="del" data-id={{ person_phone.id }} data-phone={{ person_phone.phone__number }} data-new-del='no'></div>
                                        </div>
                                    {% endif %}

                                {% endfor %}
                                <div class="cabinet-phones-column cabinet-phones-phone template" data-id='new' data-new='new' id="temlateNewFirstElement" style='display: none;'>
                                    <span>+38 (0</span>
                                    <input class="phone-number-input" type="text" autocomplete="off" disabled data-valid="true" data-wrong-values="">
                                </div>
                                <div class="cabinet-phones-column cabinet-phones-messangers template" data-id='new' data-new='new' style='display: none;'>
                                    {% for m in messengers %}
                                        <label style="display: none;">
                                            {{ m }}
                                            <input type="checkbox" name="messengers_{{ person_phone.id }}" value="{{ m.id }}" disabled>
                                            <div class="checkbox--visible"></div>
                                        </label>
                                    {% endfor %}
                                </div>
                                <div class="cabinet-phones-column cabinet-phones-radios first new template" data-id='new' data-new='new' style='display: none;'>
                                    <label>
                                        <input type="radio" name="is_delivery_phone" disabled>
                                        <div class="checkbox--visible checkbox--visible-radio"></div>
                                    </label>
                                </div>

                                <div class="cabinet-phones-column cabinet-phones-radios second template" data-id='new' data-new='new' style='display: none;'>
                                    <label>
                                        <input type="radio" name="is_main_phone" disabled}>
                                        <div class="checkbox--visible checkbox--visible-radio"></div>
                                    </label>
                                </div>
                                <div class="cabinet-phones-column del-row template" data-new='new' style='display: none;'>
                                    <div class="del" data-id='new-0'></div>
                                </div>
                            </div>

                            <h3 class="cabinet-phones-buttons">
                                <button type="button" id="addNumber">Додати ще один номер</button>
                                <button type="submit" style="display: none;">Зберегти зміни</button>
                            </h3>
                        </form>
                    </div>


                </div>
                <div class="cabinet-detail-tabs-item" id="tab-3">
                    <h3>м. Кукуєвка</h3>
                    <h3>с. Пупуївка</h3>
                </div>
            </div>
        </div>
        <form action="{% url 'root_app:del_user_phone' %}" id="delPhoneForm">
            <input type="hidden" id="phoneIdToDel" name="phone_id">
        </form>
        <a href="#delete_number-popup" id="open_delete_number_popup"></a>
        <div class="delete_number-popup mfp-hide" id="delete_number-popup">
            <h2>Ви дійсно бажаєте видалити номер:</h2>
            <h3 id="numberToDelete"></h3>
            <div class="delete_number-popup-buttons">
                <button id="confirmDelNumber">Так</button>
                <button id="cancelDelNumber">Ні</button>
            </div>

        </div>
    </div>
{% endblock %}

templates/main-page/compare.html
{% extends 'template_with_header_footer.html' %}
{% load thumbnail %}
{% load custom_tags %}

{% block title %}
    <title> Сніп-Сноп | Порівняння товарів</title>
{% endblock title %}

{% block content %}
    <div class="content-wrapper compare">
        <ul class="breadcrumbs">
            <li class="breadcrumbs__item"> <a href="/">Головна</a> </li>
            <li class="breadcrumbs__item"> Порівняння товарів </li>
       </ul>
        <div class="favorites-compare__title">
            <h2>Порівняння товарів</h2>
            <a class="link_back" id="linkBackNotCheckout" href="{{ back_link }}">До попередньої сторінки</a>
        </div>
        {% for group in grouped_dict.items %}
            <table>
                <thead>
                    <th><a href={{ group.1.category.get_absolute_url }}><h3>{{ group.1.category }}</h3></a></th>
                    {% for product in group.1.products %}
                        <th data-product-id="{{ product.id }}">
                            <a href={{ product.get_absolute_url }}><h3>{{ product }}</h3></a>
                            <span data-mode="compare" data-status="enabled" data-product-id="{{ product.id }}"></span>
                            <form  class="product_action_form" action="{{ url_product_actions }}" data-page="compare">
{#                                {% csrf_token %}#}
                                <input type="hidden" name="product_id" value="{{ product.id }}">
                                <input type="hidden" name="action" value="remove_to_compare">
                            </form>
                        </th>
                    {% endfor %}
                </thead>
                <tbody>
                    <tr>
                        <td>Вартість товару, грн</td>
                        {% for product in group.1.products %}
                            <td data-product-id="{{ product.id }}">{{ product.price|floatformat:2 }}</td>
                        {% endfor %}

                    </tr>
                    <tr>
                        <td>Вартість товару зі знижкою, грн</td>
                        {% for product in group.1.products %}
                            <td data-product-id="{{ product.id }}">{{ product.total_price|floatformat:2 }}</td>
                        {% endfor %}

                    </tr>
                    {% for gr_attr in group.1.category.groupplacement_set.all %}
                        <tr class="group-attributes"><td colspan="{{ group.1.products|length|add:'1' }}">{{ gr_attr.group }}</td></tr>
                        {% for attr in gr_attr.group.attributes.all %}
                            <tr>
                                <td>{{ attr }}</td>
                                {% for product in group.1.products %}
                                    <td data-product-id="{{ product.id }}">{{ product | get_attr_str_value:attr }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    {% endfor %}
                    {% for second_category in group.1.second_categories %}
                        {% for gr_attr in second_category.groupplacement_set.all %}
                            <tr class="group-attributes"><td colspan="{{ group.1.products|length|add:'1' }}">{{ gr_attr.group }}</td></tr>
                            {% for attr in gr_attr.group.attributes.all %}
                                <tr>
                                    <td>{{ attr }}</td>
                                    {% for product in group.1.products %}
                                        <td data-product-id="{{ product.id }}">{{ product | get_attr_str_value:attr }}</td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        {% endfor %}
                    {% endfor %}
                </tbody>
            </table>
        {% empty %}
            <h3>Ви ще не додавали товарів для порівняння</h3>
        {% endfor %}
    </div>
{% endblock %}

templates/main-page/favorites.html
{% extends 'template_with_header_footer.html' %}
{% load thumbnail %}

{% block title %}
    <title> Сніп-Сноп | Обрані товари</title>
{% endblock title %}

{% block content %}
    <div class="content-wrapper favorites">
        <ul class="breadcrumbs">
            <li class="breadcrumbs__item"> <a href="/">Головна</a> </li>
            <li class="breadcrumbs__item"> Порівняння товарів </li>
       </ul>
        <div class="favorites-compare__title">
            <h2>Обрані товари</h2>
            <a class="link_back" id="linkBackNotCheckout" href="{{ back_link }}">До попередньої сторінки</a>
        </div>
        {% for group in grouped_dict.items %}
            <h3><a href={{ group.1.category.get_absolute_url }}>{{ group.1.category }}</a></h3>
            <div class="favorites__section">
                <div class="category-products__list">
                    {% for product in group.1.products %}
                        {% include 'product_list_easy_item.html' with product=product old_price=product.price total_price=product.total_price discount_type=product.discount_type discount=product.annotated_discount id_list=fav_id_list url=url_product_actions page='favorites'%}
                    {% endfor %}
                </div>
            </div>
        {% empty %}
            <h3>Ви ще не додавали товарів до обраного</h3>
        {% endfor %}
    </div>
{% endblock %}

templates/main-page/index.html
{% extends 'template_with_header_footer.html' %}

{% block title %}
    <title> Сніп-Сноп | Головна</title>
{% endblock title %}
{% block content %}
    <div class="content-wrapper wrapper-slider">
        <div class="slider" data-slick='{"autoplay": {% if slider_config.autoplay %} true  {% else %} false {% endif %},
         "autoplaySpeed": {{ slider_config.autoplay_speed }}}'>
            {% for banner in banners %}
                <div class="slider__item">
                    <img src={{banner.image.url}} alt="">
                </div>
            {% endfor %}
        </div>
    </div>
    {% include 'main-page/top-category-section.html' %}
    <section class="about_shop">
        <div class="content-wrapper">
            <h2>Про наш магазин</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum officiis sit aut, dignissimos sapiente saepe facere laudantium necessitatibus nemo pariatur magni perferendis ad, libero magnam eligendi velit ex veritatis voluptate.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore, autem perspiciatis, doloremque beatae ut nulla illo, debitis illum iusto aspernatur deserunt nisi? Iusto totam reprehenderit animi et quos, cum rem?</p>
        </div>
    </section>
{#    {{ popular_products }}#}
    {% include 'main-page/main_page-products-section.html' with products=popular_products section_type="top_products" title='Хіти продаж'%}
    {% include 'main-page/main_page-products-section.html' with products=new_products section_type="new_products" title='Новинки'%}
{% endblock content %}

templates/main-page/main_page-products-section.html
{% load thumbnail %}
<section class={{ section_type }}>

    {% if products|length > 10 %}
        <div class="content-wrapper">
            <h2>{{ title }}</h2>
            <div class="section-arrows">
                <span class="section-arrows--left"></span>
                <span class="section-arrows--right"></span>
            </div>
            <div class="{{ section_type }}__content slider-mode">
                {% for product in products %}
                    {% include 'product_list_easy_item.html' with old_price=product.price total_price=product.total_price discount_type=product.discount_type discount=product.annotated_discount product=product.product page='listing' %}
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="content-wrapper">
            <h2>{{ title }}</h2>
            <div class="section-arrows">
                <span class="section-arrows--left slick-disabled"></span>
                <span class="section-arrows--right slick-disabled"></span>
            </div>
            <div class="{{ section_type }}__content grid-mode">
                {% for product in products %}
                    {% include 'product_list_easy_item.html' with old_price=product.price total_price=product.total_price discount_type=product.discount_type discount=product.annotated_discount product=product.product page='listing' %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
</section>

templates/main-page/top-category-section.html
{% load thumbnail %}
<section class="top-categories">
    <div class="content-wrapper top-categories__wrapper">
        <h2>Популярні категорії</h2>
        <span class="arrow arrow--left"></span>
        <span class="arrow arrow--right"></span>
        <div class="top-categories__content">
            {% for item in popular_categories %}
                <a class="top-categories__item" href="{{ item.category.get_absolute_url }}">
                    {% thumbnail item.image "300" as im %}
                        <img src="{{ im.url }}" alt="">
                    {% endthumbnail %}
                    <h4>{{ item.category.name }}</h4>
                </a>
            {% endfor %}
        </div>
    </div>
</section>