ROOTAPP/urls.py
from django.urls import path

from ROOTAPP.views import (ByNowView, CheckoutView, ProductActionsView,
                           add_email, del_user_phone,
                           get_and_check_registration_phone,
                           get_registration_name,
    # google_response,
                           logout_view,
                           regenerate_sms_token,
    # request_google_auth,
                           update_user_personal, update_user_phones,
                           verify_sms_token, get_settlement_info, ajax_updates_person_phones_info, ajax_phone_field,
                           ajax_person_field, ajax_change_phone_parameters)
from finance.views import MovementOfGoods

app_name = 'root_app'
urlpatterns = [
    path('product_actions/', ProductActionsView.as_view(), name='product_actions'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('by_now/', ByNowView.as_view(), name='by_now'),
    path('get_and_check_registration_phone/', get_and_check_registration_phone, name='get_and_check_registration_phone'),
    path('get_registration_name/', get_registration_name, name='get_registration_name'),
    path('regenerate_sms_token/', regenerate_sms_token, name='regenerate_sms_token'),
    path('verify_sms_token/', verify_sms_token, name='verify_sms_token'),
    path('logout/', logout_view, name='logout'),
    path('add_email/', add_email, name='add_email'),
    path('update_user_personal/', update_user_personal, name='update_user_personal'),
    path('update_user_phones/', update_user_phones, name='update_user_phones'),
    path('del_user_phone/', del_user_phone, name='del_user_phone'),
    path('get_settlement_info/', get_settlement_info, name='get_settlement_info'),
    path('ajax_updates_person_phones_info/<str:mode>', ajax_updates_person_phones_info, name='ajax_updates_person_phones_info'),
    path('ajax_phone_field/<str:mode>', ajax_phone_field, name='ajax_phone_field'),
    path('ajax_person_field/<str:mode>', ajax_person_field, name='ajax_person_field'),
    path('ajax_change_phone_parameters/', ajax_change_phone_parameters, name='ajax_change_phone_parameters'),
    # path('request_google_auth/', request_google_auth, name='request_google_auth'),
    # path('google_response/', google_response, name='google_response'),
]

Shop_DJ/urls.py
from baton.autodiscover import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import include, path

admin.site.site_header = 'Снип-Сноп'
admin.site.site_title = "Главная страница"
admin.site.index_title = 'Панель администрирования интернет-магазина "Снип-Сноп"'

urlpatterns = [

    path("select2/", include("django_select2.urls")),
    path('admin/', admin.site.urls),
    path("dynamic-admin-form/", include("dynamic_admin_forms.urls")),
    path('baton/', include('baton.urls')),
    path('accounts/', include('allauth.urls')),
    path('finance/', include('finance.urls')),
    path('nova_poshta', include('nova_poshta.urls')),
    path('root_app/', include('ROOTAPP.urls')),
    path('orders/', include('orders.urls')),
    path('', include('main_page.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_page/urls.py
from django.urls import path

from .views import (CabinetView, CompareView, FavoritesView, MainPageView,
                    dispatch_view)

urlpatterns = [

    path('', MainPageView.as_view(), name='home'),
    # path('<slug:slug>/', CatalogRoutingVew.as_view()),
    path('favorites/', FavoritesView.as_view(), name='favorites'),
    path('compare/', CompareView.as_view(), name='compare'),
    path('cabinet/', CabinetView.as_view(), name='cabinet'),
    path('<slug:slug>/', dispatch_view, name='category_and_product'),
    path('<slug:slug>/<str:str_url_data>/', dispatch_view, name='filteres_category'),
]
app_name = 'main_page'

orders/urls.py
from django.urls import path

from orders.views import (cancel_oneclick, create_one_click_order,
                          oneclick_add_comment, pre_create_order, get_person_info_ajax,
                          get_persons_and_contacts_by_phone_ajax, button_add_number_to_person_ajax)

urlpatterns = [
    path('by_one_click/', create_one_click_order, name='by_one_click'),
    path('oneclick_add_comment', oneclick_add_comment, name='oneclick_add_comment'),
    path('cancel_oneclick', cancel_oneclick, name='cancel_oneclick'),
    path('pre_create_order', pre_create_order, name='pre_create_order'),
    path('get_person_info_ajax', get_person_info_ajax, name='get_person_info_ajax'),
    path('get_persons_and_contacts_by_phone_ajax', get_persons_and_contacts_by_phone_ajax,
         name='get_persons_and_contacts_by_phone_ajax'),
    path('button_add_number_to_person_ajax', button_add_number_to_person_ajax, name='button_add_number_to_person_ajax'),
]
app_name = 'orders'

templates/autorize_block.html
{#<h3>User: {{ logined_user }}</h3>#}
{#<form action="{{ login_by_phone_action_url }}" id="loginByPhoneForm">#}
{#    {% csrf_token %}#}
{#    <label>#}
{#        Номер телефону#}
{#        <input class="phone-number-input" name="phonenumber" type="text" autocomplete="off" maxlength="9">#}
{#    </label>#}
{#    <label>#}
{#        Код  з СМС#}
{#        <input type="text" name="token" id="tokenInput" disabled>#}
{#    </label>#}
{#    <button type="submit">Увійти</button>#}
{#</form>#}

templates/base.html
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <!-- Useful meta tags -->
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="index, follow">
    <meta name="google" content="notranslate">
    <meta name="format-detection" content="telephone=no">
    <meta name="description" content="">
    {% block title %}
    {% endblock title %}

    {% load static %}
{#    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet">#}
{#    {{ settlement_form.media.css }}#}
{#ВРЕМЕННО ВМЕСТО ВЕРХНЕГО НА СЛУЧАЙ ОТКЛЮЧЕНИЯ ИНЕТА#}
    <link rel="stylesheet" href={% static "select2.min.css" %}>
    <link rel="stylesheet" href={% static "site-styles.css" %}>
    <link href={% static "magnific_popup/magnific-popup.css" %} rel="stylesheet">
    <link rel="stylesheet" href={% static "site-styles.css" %}>
    <link rel="stylesheet" href={% static "notyf.min.css" %}>
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.css">#}

{#    {{ form.media }}#}
</head>
<body>
    <div class="preloader slow">
        <div class="loader"></div>
    </div>

{#    <div class="preloader fast">#}
{#        <div class="loader"></div>#}
{#    </div>#}
{##}
{#    <span id="top"></span>#}
{#    <div class="page">#}
{#        <!-- Header -->#}
{#        {% include 'header.html' %}#}
{##}
{#      <!-- Main -->#}
{#        <main class="main">#}
{#            {% block content %}#}
{#            {% endblock content %}#}
{#        </main>#}
{#    </div>#}
{#    {% include 'viewed_products.html' with products=new_products %}#}
{#    {% include 'footer.html' %}#}
{#    <a class="scroll-top" href="#top"></a>#}

    {% block main_content %}
    {% endblock main_content %}


    <script src={% static "jquery-3.6.1.min.js" %}></script>
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>#}
    <script src={% static "slick.min.js" %}></script>

{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.6.0/nouislider.min.js" integrity="sha512-1mDhG//LAjM3pLXCJyaA+4c+h5qmMoTc7IuJyuNNPaakrWT9rVTxICK4tIizf7YwJsXgDC2JP74PGCc7qxLAHw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>#}
    <script src={% static "nouislider.min.js" %}></script>

{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js" integrity="sha512-d4KkQohk+HswGs6A1d6Gak6Bb9rMWtxjOa0IiY49Q3TeFd5xAzjWXDCBW9RS7m86FQ4RzM2BdHmdJnnKRYknxw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>#}
    <script src={% static "jquery.maskedinput.min.js" %}></script>

    <script src={% static "zoomsl.min.js" %}></script>
    <script src={% static "jquery.malihu.PageScroll2id.min.js" %}></script>

{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.min.js"></script>#}
    <script src={% static "select2.min.js" %}></script>

{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/i18n/uk.min.js" integrity="sha512-TDV/1TfxlJAwv/y8HVjHO/AbxfEi3JzUJhQ9HL8GqMprZTcgRggSavorvX2bYzpWyJLrav/Ub/ikmK1sd3eyTw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>#}
    <script src={% static "uk.min.js" %}></script>

    {{ settlement_form.media.js }}
{#    <script src={% static "select2.min.js" %}></script>#}

    <script src={% static "magnific_popup/jquery.magnific-popup.min.js" %}></script>
{#    <script src="https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.js"></script>#}
    <script src={% static "notyf.min.js" %}></script>
    <script src={% static "site-apps.js" %}></script>
</body>
</html>

templates/breadcrumbs.html
<ul class="breadcrumbs">
    <li class="breadcrumbs__item">
        <a href="/">Головна</a>
    </li>

    {% for cat in category.parents %}
        <li class="breadcrumbs__item">
            <a href={{ cat.0 }}>{{ cat.1 }}</a>
        </li>
    {% endfor %}

    {% if type_category == 'product' %}
        <li class="breadcrumbs__item">
            {% for cat in last_categories %}
                <a href={{ cat.get_absolute_url }}>{{ cat }}</a>
                    {% if not forloop.last %}
{#                         &nbsp ~ &nbsp#}
                        ~
                    {% endif %}
            {% endfor %}
        </li>
        </li class="breadcrumbs__item">
            <span>{{ product }}</span>
        </li>
    {% else %}
        </li class="breadcrumbs__item">
            <span>{{ category.name }}</span>
        </li>
    {% endif %}
</ul>

templates/category_listing.html
{% for product_placement in category_listing %}
    {% include 'product_list_item.html' with old_price=product_placement.price total_price=product_placement.total_price discount_type=product_placement.discount_type discount=product_placement.annotated_discount product=product_placement.product_obj minidescription_data=product_placement.minidescription_data page='listing' %}
{% endfor %}

templates/footer.html
<footer></footer>

templates/header.html
{% load custom_tags %}
<header>
    <div class="main-header">
        <div class="content-wrapper main-header__content-wrapper">
            <div class="main-header__item">
                <div class="main-header__logo">
                    <a href="/">
{#                        <img src="../media/main_page/header/logo_Snip_Snop.svg" alt="">#}
                        <img src="/media/main_page/header/logo_Snip_Snop.svg" alt="">
{#                        <img src={% static 'main_page/header/logo_Snip_Snop.svg' %} alt="">#}
                    </a>
                </div>
                <div class="main-header__logo-text">
                    <h1>Сучасне обладнання для домашніх господарств</h1>
                </div>
            </div>
            <div class="main-header__item">
                <table class="main-header__contacts">
                    {% for contact_phone in contact_phones %}
                        <tr>
                            <td class="main-header__phone-type">{{contact_phone.get_chat_links}}</td>
                            <td class="main-header__phone" itemprop="telephone">
                                <a href="tel:{{ contact_phone.phone }}">{{ contact_phone.phone.number|phone_national }}</a>
                            </td>
                        </tr>
                    {% endfor %}

                </table>
            </div>
            <div class="main-header__item">
                <ul class="schedule">
                    {% for day in schedule %}
                        {% if day.time_from and day.time_to%}
                            <li>
                                <span>{{ day.day }}</span>
                                <span class="main-header__hours">{{ day.time_from | time }}</span>
                                <span class="main-header__hours">{{ day.time_to | time}}</span>
                            </li>
                        {% else %}
                            <li>
                                <span>{{ day.day }}</span>
                                <span class="main-header__hours">Вихідний</span>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>   <!-- main-header__item -->
        </div> <!-- main-header__content -->
    </div> <!-- main-header -->
    
    <div class="sub-header">
        <div class="content-wrapper sub-header__content-wrapper">
            <div class="sub-header__search-wrapper">
                <div class="sub-header__search">
                    <form action="/">
                        <input class="sub-header__input" type="text" name="search" placeholder="шукати тут" value="">
                        <button class="sub-header__submit" type="submit">
                        </button>
                    </form>
                </div>
            </div>

            <div class="sub-header__nav">
                <ul>
                    <li><a href="#">доставка</a></li>
                    <li><a href="#">оплата</a></li>
                    <li><a href="old.html">повернення</a></li>
                </ul>
            </div>
            <div class="sub-header__userlinks">
                {% if one_click_total_amount %}
                    <span class="sub-header__user"><span>{{ one_click_total_amount }}</span></span>
                    {% else %}
                    <span class="sub-header__user"></span>
                {% endif %}

                {% if favorites_count %}
                    <a class="sub-header__favorites" href="{% url 'main_page:favorites' %}"><span>{{ favorites_count }}</span></a>
                {% else %}
                    <a class="sub-header__favorites" href="{% url 'main_page:favorites' %}"></a>
                {% endif %}
                {% if compare_count %}
                    <a class="sub-header__compare" href="{% url 'main_page:compare' %}"><span>{{ compare_count }}</span></a>
                {% else %}
                    <a class="sub-header__compare" href="{% url 'main_page:compare' %}"></a>
                {% endif %}
                {% if basket_total.total_amount %}
                    <span class="sub-header__basket" href="#"><span>{{ basket_total.total_amount }}</span></span>
                {% else %}
                    <span class="sub-header__basket" href="#"></span>
                {% endif %}
                {% include 'user_content.html' %}
            </div>
        </div> <!-- sub-header__content -->
    </div> <!-- sub-header -->

    <nav class="top-catalog">
        <div class="top-catalog__100w-bg"></div>
        <div class="content-wrapper top-catalog__content-wrapper">
            <ul class="top-catalog__first-level-list">
                {% for menu_item_1 in menu_items %}
                    <li class="top-catalog__first-level-item">
                        {% if  menu_item_1.get_link %}
                            <a class="top-catalog__first-level-link-wrapper" href={{ menu_item_1.get_link }}>
                                {% if menu_item_1.image %}
                                    <img src={{menu_item_1.image.url}} alt="alt">
                                {% endif %}
                                <h2>{{ menu_item_1.title }}</h2>
                            </a>
                        {% else %}
                            <div class="top-catalog__first-level-link-wrapper">
                                {% if menu_item_1.image %}
                                    <img src={{menu_item_1.image.url}} alt="alt">
                                {% endif %}
                                <h2>{{ menu_item_1.title }}</h2>
                            </div>
                        {% endif %}
                        {% if header_config.menu_height %}
                            <style>
                                .top-catalog__first-level-link-wrapper {height: {{ header_config.menu_height }};}
                            </style>
                        {% endif %}
                        <div class="top-catalog__second-level-list-wrapper--w100">
                            <ul class="top-catalog__second-level-list">
                                {% for menu_item_2 in menu_item_1.children.all %}
                                    <li class="top-catalog__second-level-item">
                                        {% if  menu_item_2.get_link %}
                                            <a href={{ menu_item_2.get_link }}>{{ menu_item_2.title }}</a>
                                        {% else %}
                                            {{ menu_item_2.title }}
                                        {% endif %}
                                        <ul class="top-catalog__third-level-list">
                                            {% for menu_item_3 in menu_item_2.children.all %}
                                                <li class="top-catalog__third-level-item top-catalog__third-level-item">
                                                    {% if  menu_item_3.get_link %}
                                                        <a href={{ menu_item_3.get_link }}>{{ menu_item_3.title }}</a>
                                                    {% else %}
                                                        {{ menu_item_3.title }}
                                                    {% endif %}
                                                <ul class="top-catalog__last-level-list">
                                                    {% for menu_item_4 in menu_item_3.children.all %}
                                                        {% if  menu_item_4.get_link %}
                                                            <li><a href={{ menu_item_4.get_link }}>{{ menu_item_4.title }}</a></li>
                                                        {% else %}
                                                            {{ menu_item_4.title }}
                                                        {% endif %}
                                                        {% endfor %}
                                                    </ul>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>  <!-- top-catalog content-wrapper -->
    </nav>
</header>

<!-- <div class="margin-header"></div> -->
<div class="darker-out-topmenu"></div>

templates/template_with_header_footer.html
{% extends 'base.html' %}

{% block main_content %}

    <div class="preloader fast">
    <div class="loader"></div>
    </div>

    <span id="top"></span>
    <div class="page">
    <!-- Header -->
    {% include 'header.html' %}

    <!-- Main -->
    <main class="main">
    {% block content %}
    {% endblock content %}
    </main>
    </div>
    {% include 'viewed_products.html' with products=new_products %}
    {% include 'autorize_block.html' %}
    {% include 'footer.html' %}
    <a class="scroll-top" href="#top"></a>
{% endblock main_content %}

templates/user_content.html
{% load thumbnail %}
{% load custom_tags %}
{% load socialaccount %}

<div class="user-content user-content__basket" id="basket">
    <div class="user-content__basket-list-wrapper">
        <div class="user-content__basket-list">
            {% for pr in products_obj_in_basket %}
                <div class="user-content__basket-item">
                    <div class="user-content__basket-item-img">
                        {% thumbnail pr.product.thumb "80" as im %}
                            <a href={{ pr.product.get_absolute_url }}><img src="{{ im.url }}"></a>
                        {% endthumbnail %}
                    </div>

                    <div class="user-content__basket-item-info">
                        <a href={{ pr.product.get_absolute_url }}><h4>{{ pr.product }}</h4></a>
                        <div class="user-content__basket-item-calculate">
                            <div class="user-content__basket-item-price">{{ pr.price }} ₴</div>
                            <div class="user-content__basket-item-amount">
                                <input type="number" min="1" name="amount" value="{{ pr.amount }}" data-product_id="{{ pr.product.id }}" data-action="change_amount" autocomplete="off">, шт
                            </div>
                            <div class="user-content__basket-item-total">Всього: <span>{{ pr.total|floatformat:2 }} ₴</span></div>
                        </div>
                    </div>
                    <span class="close"><span data-product_id="{{ pr.product.id }}" data-action="remove_from_basket"></span></span>
                </div>
            {% empty %}
                <h2 id="empty_basket">Кошик порожній</h2>
            {% endfor %}
        </div>

        <form id="update_basket" action="{{ url_product_actions }}">
{#            {% csrf_token %}#}
            <input type="hidden" name='product_id' value="">
            <input type="hidden" name="action" value="">
            <input type="hidden" name="amount" value="">
        </form>

    </div>
{#    {% if products_obj_in_basket %}#}
{#        <div class="user-content__basket-total visible">#}
{#    {% else %}#}
{#        <div class="user-content__basket-total">#}
{#    {% endif %}#}
{#    <div class="user-content__basket-total {{ products_obj_in_basket | variants:'visible'}}">#}
    <div class="user-content__basket-total {% values_by_condition products_obj_in_basket 'visible' %}">
        <a href="{% url 'root_app:checkout' %}">Оформити</a>

        <div class="user-content__basket-total--ammount">
            <span>{{ basket_total.total_amount }}</span> шт
        </div>
        <div class="user-content__basket-total--summ">
            на суму: <span>{{ basket_total.total_sum|floatformat:2  }} ₴</span>
        </div>
    </div>
    <div class="hide_status"></div>
</div>

<div class="user-content user-content__personal" id="userContent">
    <div class="user-content__personal-nav">
        <span class="user-content__personal-nav-item personal-nav_item--active" id="oneClick">Мої заявки (<span>{{ one_click_obj_list.count }}</span>)</span>
        <span class="user-content__personal-nav-item" id="orders">Мої замовлення (0)</span>
        <span class="user-content__personal-nav-item" id="cabinet">Мій кабінет</span>
    </div>
    <div class="user-content__personal-content">
        <div class="user-content__personal-tab tab-active" data-id="oneClick">
            <div class="user-content__personal-oneclick">
                {% for oneclick in one_click_obj_list%}
                    {% include "one_click_user_section_item.html" %}
                    <h3 id="noOneclicks" style="display: none">Немає активних заявок з цього пристрою</h3>
                    {% empty %}
                    <h3 id="noOneclicks">Немає активних заявок з цього пристрою</h3>
                {% endfor %}
            </div>
        </div>
        <div class="user-content__personal-tab" data-id="orders">

        </div>

        <div class="user-content__personal-tab cabinet" data-id="cabinet">
            <h3 class='user-content__personal-item-title' id="loginTitle">{{ cabinet_title_text }}</h3>
            {% if allow_verify_time_delta %}
                <h3>Ви зможете ввести пароль через <span>${interval}</span> секунд </h3>
            {% endif %}
            <form action={{ get_and_check_registration_phone_action_url }} id="sendRegistrationPhoneForm" style="{% values_by_condition user.is_authenticated 'display: none;' %}">
{#                {% csrf_token %}#}
                <label class='cabinet__login-section user-content__personal-item'>
                    +38(0
                    <input class="phone-number-input" name="phonenumber" type="text" autocomplete="off" maxlength="9">
                    <div>
                        <button type="submit">Підтвердити</button>
                    </div>
                    <h3 id="wrongRegistrationPhone" style="display: none;">Такий номер не існує</h3>
                </label>
            </form>

            <form action={{ get_registration_name_action_url }} id="sendRegistrationNameForm" style="display: none;">
{#                {% csrf_token %}#}
                <label class='cabinet__login-section user-content__personal-item'>
                    Ваше ім'я
                    <input type="text" name="name" id="registrationNameInput">
                    <div>
                        <button type="submit">Підтвердити</button>
                    </div>
                </label>
            </form>

            <form action={{ verify_sms_token_action_url }} id="verifySmsTokenForm" style="display: none;">
{#                {% csrf_token %}#}
                <div class='cabinet__login-section user-content__personal-item'>
                    <label>
                        Одноразовий пароль  з СМС
                        <input type="text" name="token" id="tokenInput" maxlength="6">
                        <span id="tokenValidityTimerIndicator" style="display: none">(дійсний &nbsp<span></span>c)</span>
                        <div>
                            <button type="submit">Підтвердити</button>
                        </div>
                    </label>

                    <span class="get_token_actions" id="regenerateSmsTokenBtn">Відправити новий код підтвердження</span>
                    <span class="get_token_actions" id="regenerateSmsTokenTimer" style="display: none; cursor: auto; opacity: 50%">Запросити код ще раз можливо через <span></span> с</span>
                    <span class="get_token_actions" id="changeNumber">Вказати інший номер телефону</span>
                </div>
            </form>
            <form action={{ regenerate_sms_token_action_url }} id='regenerateSmsTokenForm'>
{#                {% csrf_token %}#}
            </form>


            <form action={{ logout_action_url }} id='logoutForm' style="{% values_by_condition user.is_authenticated '' 'display: none;' %}">

                <div class="cabinet__login-section user-content__personal-item">
{#                    {% csrf_token %}#}
                    <div class="logined_links">
                        <a class="cabinet_link" href="{% url 'main_page:cabinet' %}">Перейти в мій кабінет</a>
                        <button type="submit" id="logoutBtn">Вийти</button>
                    </div>
                </div>
            </form>

            <div class="cabinet__separator" style="{% values_by_condition user.is_authenticated 'display: none;' %}">
                <hr>
                <span id="socialSeparatorText">або авторизутесь через соціальні мережі</span>
                <hr>
            </div>
            <div class="cabinet__social" id="socialLoginSection" style="{% values_by_condition user.is_authenticated 'display: none;' %}">

                {% get_providers as socialaccount_providers %}
                {% for provider in socialaccount_providers %}
                    <div class="cabinet__social-item">
                        <a class="cabinet__social-section" title="{{provider.name}}"href="{% provider_login_url provider.id process='login' scope=scope auth_params=auth_params %}">
                            <div class="cabinet__social-icon {{provider.id}}"></div>
                            <div class="cabinet__social-text">Увійти через {{provider.name}}</div>
                        </a>
                    </div>

                {% endfor %}
            </div>
            <div class="cabinet__separator" style="{% values_by_condition user.is_authenticated 'display: none;' %}">
                <hr>
                <span>або авторизутесь за допомогою електронної пошти</span>
                <hr>
            </div>
            <div class="cabinet__social" style="{% values_by_condition user.is_authenticated 'display: none;' %}">
                <div class="cabinet__social-item">
                    <a href="{% url 'account_login' %}" class="cabinet__social-section"> <div class="cabinet__social-text">Увійти</div></a>
                </div>
                <div class="cabinet__social-item">
                    <a href="{% url 'account_signup' %}" class="cabinet__social-section">  <div class="cabinet__social-text">Зареєструватись</div></a>
                </div>
            </div>

            <div class="social_settings_link" id="socialSettingsSection" style="{% values_by_condition user.is_authenticated '' 'display: none;' %}">
                <h3><a href="{% url 'socialaccount_connections' %}">Перейти до налаштування входу через соцмережі</a></h3>
            </div>

            <div class="email_login_section" style="{% values_by_condition show_email_login_section '' 'display: none;'%}">
                <h3><span id="emailLoginSectionButton">Налаштувати вхід через електронну пошту і пароль</span></h3>
                <form action="{% url 'root_app:add_email' %}" id="addEmail" style="display: none;">
                    {{ email_form }}
                    <button type="submit">OK</button>
                </form>
            </div>
            <div class="set_password_section" style="{% values_by_condition show_set_password_link '' 'display: none;'%}">
                <h3><a href="{% url 'account_reset_password' %}">Задати або відновити пароль</a></h3>
            </div>
            <div class="change_password_section" style="{% values_by_condition show_change_password_link '' 'display: none;'%}">
                <h3><a href="{% url 'account_change_password' %}">Змінити пароль</a></h3>
            </div>

        </div>
    </div>
</div>