Shop_DJ/urls.py
from baton.autodiscover import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import include, path

admin.site.site_header = 'Снип-Сноп'
admin.site.site_title = "Главная страница"
admin.site.index_title = 'Панель администрирования интернет-магазина "Снип-Сноп"'

urlpatterns = [

    path("select2/", include("django_select2.urls")),
    path('admin/', admin.site.urls),
    path("dynamic-admin-form/", include("dynamic_admin_forms.urls")),
    path('baton/', include('baton.urls')),
    path('accounts/', include('allauth.urls')),
    path('finance/', include('finance.urls')),
    path('nova_poshta', include('nova_poshta.urls')),
    path('root_app/', include('ROOTAPP.urls')),
    path('orders/', include('orders.urls')),
    path('', include('main_page.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nova_poshta/urls.py
from django.urls import path

from nova_poshta.views import (get_delivery_cost, update_cities,
                               update_settlements, update_warehouses, update_streets, get_streets)

app_name = 'nova_poshta'
urlpatterns = [
    path('update_settlements/', update_settlements, name='update_settlements'),
    path('update_cities/', update_cities, name='update_cities'),
    path('update_warehouses/', update_warehouses, name='update_warehouses'),
    path('update_streets/', update_streets, name='update_streets'),
    path('get_delivery_cost/', get_delivery_cost, name='get_delivery_cost'),
    path('get_streets/', get_streets, name='get_streets'),
]

orders/urls.py
from django.urls import path

from orders.views import (cancel_oneclick, create_one_click_order,
                          oneclick_add_comment, pre_create_order, get_person_info_ajax,
                          get_persons_and_contacts_by_phone_ajax, button_add_number_to_person_ajax)

urlpatterns = [
    path('by_one_click/', create_one_click_order, name='by_one_click'),
    path('oneclick_add_comment', oneclick_add_comment, name='oneclick_add_comment'),
    path('cancel_oneclick', cancel_oneclick, name='cancel_oneclick'),
    path('pre_create_order', pre_create_order, name='pre_create_order'),
    path('get_person_info_ajax', get_person_info_ajax, name='get_person_info_ajax'),
    path('get_persons_and_contacts_by_phone_ajax', get_persons_and_contacts_by_phone_ajax,
         name='get_persons_and_contacts_by_phone_ajax'),
    path('button_add_number_to_person_ajax', button_add_number_to_person_ajax, name='button_add_number_to_person_ajax'),
]
app_name = 'orders'

nova_poshta/forms.py
from allauth.account.forms import ResetPasswordForm
from django import forms
from django_select2.forms import ModelSelect2Widget

from ROOTAPP.models import PersonAddress
from nova_poshta.models import Settlement, SettlementArea, Warehouse, CityArea, City, Street


# from django_select2 import forms as s2forms


# class MyCustomResetPasswordForm(ResetPasswordForm):
#     email = forms.EmailField(
#         label="e-mail адреса",
#         required=True,
#         initial='asd@df.ua',
#         widget=forms.TextInput(
#             attrs={
#                 "type": "email",
#                 "placeholder": "e-mail адр",
#                 "autocomplete": "email",
#             }
#         ),
#     )


class SettlementForm(forms.Form):
    area = forms.ModelChoiceField(
        queryset=SettlementArea.objects.all(),
        label="Область",
        widget=ModelSelect2Widget(
            model=SettlementArea,
            search_fields=['description_ua__icontains', 'description_ru__icontains'],
            attrs={'data-placeholder': 'назва області'}
        )
    )

    settlement = forms.ModelChoiceField(
        queryset=Settlement.objects.all(),
        label="Населений пункт",
        widget=ModelSelect2Widget(
            model=Settlement,
            search_fields=('description_ua__icontains', 'description_ru__icontains'),
            dependent_fields={'area': 'area'},
            max_results=50,
            attrs={'data-placeholder': 'назва населеного пункту'}
        )
    )


class CityForm(forms.Form):
    area = forms.ModelChoiceField(
        queryset=CityArea.objects.all(),
        label="Область",
        widget=ModelSelect2Widget(
            model=CityArea,
            search_fields=['description_ua__icontains', 'description_ru__icontains'],
            attrs={'data-placeholder': 'назва області'}
        )
    )

    city = forms.ModelChoiceField(
        queryset=City.objects.all(),
        label="Город",
        widget=ModelSelect2Widget(
            model=City,
            search_fields=('description_ua__icontains', 'description_ru__icontains'),
            dependent_fields={'area': 'area'},
            max_results=50,
            attrs={'data-placeholder': 'назва міста'}
        )
    )


area_widget = ModelSelect2Widget(
    model=SettlementArea,
    search_fields=['description_ua__icontains', 'description_ru__icontains'],
    attrs={'data-placeholder': 'назва області', 'style': 'width: 80%;',
           'data-minimum-input-length': '0'}
)

settlement_widget = ModelSelect2Widget(
    model=Settlement,
    search_fields=('description_ua__icontains', 'description_ru__icontains'),
    dependent_fields={'area': 'area'},
    max_results=50,
    attrs={'data-placeholder': 'назва населеного пункту', 'style': 'width: 80%;'}
)

warehouse_widget = ModelSelect2Widget(
    model=Warehouse,
    search_fields=('description_ua__icontains', 'description_ru__icontains', 'type_warehouse__description_ru__icontains'),
    dependent_fields={'settlement': 'settlement'},
    max_results=50,
    # minimum_results_for_search=1,
    attrs={'data-placeholder': 'отделение', 'style': 'width: 80%;',
           'data-minimum-input-length': '0'}
)


street_widget = ModelSelect2Widget(
    model=Street,
    search_fields=('description_ua__icontains',),
    dependent_fields={'city': 'city'},
    max_results=50,
    minimum_results_for_search=10,
    attrs={'data-placeholder': 'улица или село', 'style': 'width: 80%;',
           'data-minimum-input-length': '0'}
)

address_for_order_widget = ModelSelect2Widget(
    model=PersonAddress,
    search_fields=('settlement__description_ua__icontains', 'settlement__description_ua__icontains'),
    dependent_fields={'person': 'person'},
    max_results=10,
    minimum_results_for_search=9,
    attrs={'data-placeholder': 'выберете адрес доставки', 'style': 'width: 80%;',
           'data-minimum-input-length': '0'}
)

nova_poshta/views.py
import json
import uuid

import requests
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.html import format_html
from jsonview.decorators import json_view

from nova_poshta.models import City, Settlement, Warehouse, Street
from nova_poshta.services import (build_objects_to_create, city_parameters,
                                  get_and_apply_changes, get_np_api_response,
                                  settlement_parameters, timeout_limit,
                                  warehouse_parameters, street_parameters)


def update_np_catalogs(request, obj_type):
    types_settings = {
        'Settlement': ("getSettlements", settlement_parameters),
        'City': ("getCities", city_parameters),
        'Warehouse': ("getWarehouses", warehouse_parameters),
        'Street': ("getStreet", street_parameters),
    }
    called_method, data_structure = types_settings[obj_type.__name__]

    print('called_method - ', called_method)

    objects_request_dict = {
        "modelName": "Address",
        "calledMethod": called_method,
        "methodProperties": {
            "Limit": '500' if obj_type == Warehouse or obj_type == Street else '150'
        }
    }
    sess = requests.Session()
    data, message_text = request.GET, ''
    search_by_descr, search_by_settlement, search_by_city = False, False, False
    objects_total_position, total_added_objects_count, total_edited_objects_count = 1, 0, 0

    objects_limit = int(objects_request_dict['methodProperties']['Limit'])

    # перебирать все города в базе и запрашивать по ним улицы если только не указан в форме определенный город
    search_data = City.objects.values_list('ref', flat=True) if obj_type == Street and 'city' not in data.keys() \
        else [None]
    print('ALL SEARCH DATA -', search_data)
    cities_list_len = len(search_data)
    city_count = 1
    # 'это можеть быть одно действие или последовательный запрос улиц по городу / гороам
    for search_data in search_data:
        search_data = str(search_data)
        objects_position, added_objects_count, edited_objects_count = 1, 0, 0
        page, ln = 1, objects_limit
        city = ''
        if data:
            print('FORM DATA: ', data)
            if 'search_name' in data.keys():
                search_by_descr = True
                objects_request_dict['methodProperties']['FindByString'] = (search_name := data['search_name'])
                message_text = f'Обновление списка элементов справочника по запросу {search_name} <br>'
            if 'settlement' in data.keys():
                search_by_descr = True
                objects_request_dict['methodProperties']['SettlementRef'] = (search_ref := data['settlement'])
                search_name = Settlement.objects.get(ref=search_ref)
                message_text = f'Обновление справочника отделений по населенному пункту {search_name}<br>'
            if 'city' in data.keys():
                search_by_descr = True
                objects_request_dict['methodProperties']['CityRef'] = (search_ref := data['city'])
                search_name = City.objects.get(ref=search_ref)
                message_text = f'Обновление справочника улиц по городу {search_name} <br>'
        elif search_data and search_data != 'None':
            objects_request_dict['methodProperties']['CityRef'] = search_data
            search_name = City.objects.get(ref=search_data)
            message_text += f'<h5>Обновление справочника улиц по городу {search_name}</h5>>'
            city = City.objects.get(ref=search_data)
            print(f'Запрос списка улиц по городу: #{city_count} из {cities_list_len} -', city)

        while ln == objects_limit:
            objects_to_create, changed_objects, changed_fields = [], [], set()
            new_objects_names, changed_objects_names = [], []
            objects_request_dict["methodProperties"]["Page"] = str(page)
            print(f'Запрос страницы сервера #{page}')

            np_api_response = get_np_api_response(objects_request_dict, sess)
            objects_response_data = np_api_response.data
            objects_response_errors = np_api_response.errors
            if objects_response_errors:
                messages.add_message(request, messages.ERROR, objects_response_errors)
                break
            else:
                ln = len(all_objects_data := objects_response_data)

                print(elements_countown := f'Получены данные {ln} элементов справочника, лимит: {objects_limit}')
                print()
                message_text += f'<p>{elements_countown}</p>'
                if not search_data:
                    message_text += f'Загрузка страницы №{page} (по {objects_limit} объектов на старнице) <br>'
                page += 1

                for obj_data in all_objects_data:
                    if obj_type == Warehouse:
                        object_name = obj_data['DescriptionRu']
                    if obj_type == Street:
                        obj_data['CityRef'] = objects_request_dict['methodProperties']['CityRef']
                        object_name = f"{obj_data['StreetsType']} {obj_data['Description']}"
                    else:
                        region = f", {obj_data['RegionsDescriptionRu']}" if obj_type == Settlement else ''
                        description_ru = f"{obj_data['DescriptionRu']}/" if 'DescriptionRu' in obj_data.keys() else ''
                        area_description = f"({obj_data['AreaDescriptionRu']}{region})" \
                            if 'AreaDescriptionRu' in obj_data.keys() else ''
                        object_name = f"№{objects_position}: {description_ru}{obj_data['Description']} " \
                                      f"{area_description}"
                    if search_by_descr:
                        message_text += f'Найдено {object_name} <br>'
                        print(f'Найдено {object_name}')

                    # проверить есть ли ужк такой объект в локальной базе, если да то проверить изменения в нем в API
                    if obj_type.objects.filter(ref=obj_data['Ref']).exists():
                        object_changes_data = get_and_apply_changes(
                            obj_type.objects.get(ref=obj_data['Ref']), data_structure, obj_data
                        )
                        if object_changes_data['changed']:
                            total_edited_objects_count += 1
                            edited_objects_count += 1
                            message_text += object_changes_data['new_message_text']
                            changed_objects.append(object_changes_data['changed_obj'])
                            changed_fields.update(object_changes_data['changed_fields'])
                            print(f'Изменено: {object_name}')

                    else:
                        result_build_objects_to_create = build_objects_to_create(obj_data, obj_type, data_structure)
                        if result_build_objects_to_create['error_messages']:
                            messages.add_message(
                                request, messages.ERROR, result_build_objects_to_create['error_messages'])
                            break
                        else:
                            new_objects = result_build_objects_to_create['obj_to_create']
                            mess_new_obj = result_build_objects_to_create['messages']
                            objects_to_create.append(new_objects)
                            if not search_data:
                                message_text += mess_new_obj
                            new_objects_names.append(object_name)
                            print(f'Добавлено: {object_name}')
                            total_added_objects_count += 1
                            added_objects_count += 1
                    objects_total_position += 1
                    objects_position += 1
                # for obj_data in all_objects_data / конец цикла перебора данных API
                print('-' * 80)

                if len(objects_to_create):
                    obj_type.objects.bulk_create(objects_to_create)
                    if not search_data:
                        message_text += 'Добавлено^<ul>'
                        for added in new_objects_names:
                            message_text += f'<li>{added}</li>'
                        message_text += '</ul>'

                if len(changed_objects):
                    obj_type.objects.bulk_update(changed_objects, changed_fields)
                    message_text += 'Изменено^<ul>'
                    for edited in changed_objects_names:
                        message_text += f'<li>{edited}</li>'
                    message_text += '</ul>'

        city_count += 1
        if search_data:
            message_text += f'<p>добавлено {added_objects_count} улиц, изменено {edited_objects_count} улиц</p> <br>'
    print('=' * 80)
    sess.close()
    total_info = f'На сервере просмотрено {objects_total_position - 1} элементов справочника.<br>Всего добавлено элементов' \
                 f' {total_added_objects_count}, всего изменено элементов {total_edited_objects_count} '
    messages.add_message(request, messages.SUCCESS, format_html(message_text))
    messages.add_message(request, messages.SUCCESS, format_html(total_info))
    print(total_info)
    print('=' * 80, '<br>')


def update_settlements(request):
    update_np_catalogs(request, Settlement)
    return HttpResponseRedirect(reverse('admin:nova_poshta_settlement_changelist'))


def update_cities(request):
    update_np_catalogs(request, City)
    return HttpResponseRedirect(reverse('admin:nova_poshta_city_changelist'))


def update_warehouses(request):
    update_np_catalogs(request, Warehouse)
    return HttpResponseRedirect(reverse('admin:nova_poshta_warehouse_changelist'))


def update_streets(request):

templates/nova_poshta/admin_update_streets.html
{% load static %}
{{ city_form.media.css }}
<link rel="stylesheet" href={% static "select2.min.css" %}>
<p>
    <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Обновить список улиц
    </a>
</p>
<div class="collapse" id="collapseExample">
    <div class="card card-body">
        <div class="update_warehouses_section">
            <a class="update_all" href="{% url 'nova_poshta:update_streets' %}">Обновить весь список улиц </a>
            <h5 class="update_by_settlement_titile">Обновление по городу</h5>

            <h6>Выберите населенный пункт:</h6>

            <form action="{% url 'nova_poshta:update_streets' %}">
                <div style="display: flex" class="select_settlement">

                    {{ city_form.as_p }}

                </div>
                <button type="submit" class="btn btn-primary">Обновить</button>
            </form>
        </div>
    </div>
</div>
{{ city_form.media.js }}


<style>
    .update_warehouses_section {
        outline: none;
    }

    .update_all {
        background-color: #e1d483;
        padding: .5rem 1rem;
        font-size: 1.2rem;
        font-weight: 600;
        border-radius: .3rem;
    }

    .update_by_settlement_titile {
        text-align: center;
        font-weight: 600;
        text-decoration: underline;
        margin: 2rem  0;
        background-color: #a09cd3;
        padding: 1.2rem;
    }

    .update_warehouses_section h6 {
        margin-bottom: 1.5rem;
        text-decoration: underline;
    }
    
    .select_settlement {
        max-width: 80rem;
    }

    .select_settlement p:first-child span {
        width: 20rem;
    }

    .select_settlement p:nth-child(2) span {
        width: 38rem;
    }

    .select_settlement p:nth-child(2) {
        margin-left: 2rem;
    }

    .collapse {
        margin-bottom: 2rem;
    }
</style>

templates/nova_poshta/admin_update_warehouses.html
{% load static %}
{{ settlement_form.media.css }}
<link rel="stylesheet" href={% static "select2.min.css" %}>
<p>
    <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Обновить список отделений
    </a>
</p>
<div class="collapse" id="collapseExample">
    <div class="card card-body">
        <div class="update_warehouses_section">
            <a class="update_all" href="{% url 'nova_poshta:update_warehouses' %}">Обновить весь список отделений </a>
            <h5 class="update_by_settlement_titile">Обновление по населенному пункту</h5>

            <h6>Выберите населенный пункт:</h6>

            <form action="{% url 'nova_poshta:update_warehouses' %}">
                <div style="display: flex" class="select_settlement">

                    {{ settlement_form.as_p }}

                </div>
                <button type="submit" class="btn btn-primary">Обновить</button>
            </form>
        </div>
    </div>
</div>
{{ settlement_form.media.js }}


<style>
    .update_warehouses_section {
        outline: none;
    }

    .update_all {
        background-color: #e1d483;
        padding: .5rem 1rem;
        font-size: 1.2rem;
        font-weight: 600;
        border-radius: .3rem;
    }

    .update_by_settlement_titile {
        text-align: center;
        font-weight: 600;
        text-decoration: underline;
        margin: 2rem  0;
        background-color: #a09cd3;
        padding: 1.2rem;
    }

    .update_warehouses_section h6 {
        margin-bottom: 1.5rem;
        text-decoration: underline;
    }
    
    .select_settlement {
        max-width: 80rem;
    }

    .select_settlement p:first-child span {
        width: 20rem;
    }

    .select_settlement p:nth-child(2) span {
        width: 38rem;
    }

    .select_settlement p:nth-child(2) {
        margin-left: 2rem;
    }

    .collapse {
        margin-bottom: 2rem;
    }
</style>

templates/nova_poshta/button_update_cities.html
<a href="{% url 'nova_poshta:update_cities' %}">Обновить весь список городов новой почты</a>
<form action="{% url 'nova_poshta:update_cities' %}">
    <label>
        Поисковая фраза
        <input type="text" name="search_name">
    </label>
    <button type="submit">Обновить по названию</button>
</form>

templates/nova_poshta/button_update_settlements.html
<a href="{% url 'nova_poshta:update_settlements' %}">Обновить весь список населенных пунктов Украины</a>
<form action="{% url 'nova_poshta:update_settlements' %}">
    <label>
        Поисковая фраза
        <input type="text" name="search_name">
    </label>
    <button type="submit">Обновить по названию</button>
</form>